spring:
  application:
    name: vmsapp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbdata
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
  thymeleaf:
    cache: false
server:
  port: 9988

